name: OpenLDM
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ca-certificates
  - python
  - readline
  - r-base
  - r-rgdal
  - r-raster
  - r-data.table
  - gdal
  - pyqt 
  - pip
  - pip:
    - rpy2
