# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LULCgui3.5.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LULCModel(object):
    def setupUi(self, LULCModel):
        LULCModel.setObjectName("LULCModel")
        LULCModel.resize(1005, 751)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/ilulc/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LULCModel.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LULCModel)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDataPreparation = QtWidgets.QWidget()
        self.tabDataPreparation.setObjectName("tabDataPreparation")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabDataPreparation)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabDataPreparation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gbProjectSection = QtWidgets.QGroupBox(self.groupBox_4)
        self.gbProjectSection.setObjectName("gbProjectSection")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.gbProjectSection)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.leProjectDirectory_DataPreparationInputSectionProjectSection = QtWidgets.QLineEdit(self.gbProjectSection)
        self.leProjectDirectory_DataPreparationInputSectionProjectSection.setText("")
        self.leProjectDirectory_DataPreparationInputSectionProjectSection.setObjectName("leProjectDirectory_DataPreparationInputSectionProjectSection")
        self.gridLayout_14.addWidget(self.leProjectDirectory_DataPreparationInputSectionProjectSection, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gbProjectSection)
        self.label_6.setObjectName("label_6")
        self.gridLayout_14.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gbProjectSection)
        self.label_5.setObjectName("label_5")
        self.gridLayout_14.addWidget(self.label_5, 0, 0, 1, 1)
        self.pbSelectDirectory_DataPreparationInputSectionProjectSection = QtWidgets.QPushButton(self.gbProjectSection)
        self.pbSelectDirectory_DataPreparationInputSectionProjectSection.setObjectName("pbSelectDirectory_DataPreparationInputSectionProjectSection")
        self.gridLayout_14.addWidget(self.pbSelectDirectory_DataPreparationInputSectionProjectSection, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gbProjectSection)
        self.label_7.setEnabled(False)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_14.addWidget(self.label_7, 0, 5, 1, 1)
        self.leNAValue_DataPreparationInputSectionProjectSection = QtWidgets.QLineEdit(self.gbProjectSection)
        self.leNAValue_DataPreparationInputSectionProjectSection.setObjectName("leNAValue_DataPreparationInputSectionProjectSection")
        self.gridLayout_14.addWidget(self.leNAValue_DataPreparationInputSectionProjectSection, 0, 4, 1, 1)
        self.sbGridsize_DataPreparationInputSectionProjectSection = QtWidgets.QSpinBox(self.gbProjectSection)
        self.sbGridsize_DataPreparationInputSectionProjectSection.setEnabled(False)
        self.sbGridsize_DataPreparationInputSectionProjectSection.setMinimum(65)
        self.sbGridsize_DataPreparationInputSectionProjectSection.setMaximum(250000)
        self.sbGridsize_DataPreparationInputSectionProjectSection.setSingleStep(50)
        self.sbGridsize_DataPreparationInputSectionProjectSection.setProperty("value", 1000)
        self.sbGridsize_DataPreparationInputSectionProjectSection.setObjectName("sbGridsize_DataPreparationInputSectionProjectSection")
        self.gridLayout_14.addWidget(self.sbGridsize_DataPreparationInputSectionProjectSection, 0, 6, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.gbProjectSection, 0, 0, 1, 1)
        self.gbDataInput = QtWidgets.QGroupBox(self.groupBox_4)
        self.gbDataInput.setObjectName("gbDataInput")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.gbDataInput)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.leT0File_DataPreparationInputSectionDataInput = QtWidgets.QLineEdit(self.gbDataInput)
        self.leT0File_DataPreparationInputSectionDataInput.setEnabled(True)
        self.leT0File_DataPreparationInputSectionDataInput.setText("")
        self.leT0File_DataPreparationInputSectionDataInput.setObjectName("leT0File_DataPreparationInputSectionDataInput")
        self.gridLayout_15.addWidget(self.leT0File_DataPreparationInputSectionDataInput, 0, 1, 1, 1)
        self.pbSelectFileT0File_DataPreparationInputSelectionDataInput = QtWidgets.QPushButton(self.gbDataInput)
        self.pbSelectFileT0File_DataPreparationInputSelectionDataInput.setObjectName("pbSelectFileT0File_DataPreparationInputSelectionDataInput")
        self.gridLayout_15.addWidget(self.pbSelectFileT0File_DataPreparationInputSelectionDataInput, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gbDataInput)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 1, 3, 1, 1)
        self.leT1Year_DataPreparationInputSectionDataInput = QtWidgets.QLineEdit(self.gbDataInput)
        self.leT1Year_DataPreparationInputSectionDataInput.setText("")
        self.leT1Year_DataPreparationInputSectionDataInput.setMaxLength(4)
        self.leT1Year_DataPreparationInputSectionDataInput.setObjectName("leT1Year_DataPreparationInputSectionDataInput")
        self.gridLayout_15.addWidget(self.leT1Year_DataPreparationInputSectionDataInput, 1, 4, 1, 1)
        self.leAreaOfInterest_DataPreparationInputSectionDataInput = QtWidgets.QLineEdit(self.gbDataInput)
        self.leAreaOfInterest_DataPreparationInputSectionDataInput.setEnabled(True)
        self.leAreaOfInterest_DataPreparationInputSectionDataInput.setText("")
        self.leAreaOfInterest_DataPreparationInputSectionDataInput.setObjectName("leAreaOfInterest_DataPreparationInputSectionDataInput")
        self.gridLayout_15.addWidget(self.leAreaOfInterest_DataPreparationInputSectionDataInput, 2, 1, 1, 1)
        self.leT0Year_DataPreparationInputSectionDataInput = QtWidgets.QLineEdit(self.gbDataInput)
        self.leT0Year_DataPreparationInputSectionDataInput.setText("")
        self.leT0Year_DataPreparationInputSectionDataInput.setMaxLength(4)
        self.leT0Year_DataPreparationInputSectionDataInput.setObjectName("leT0Year_DataPreparationInputSectionDataInput")
        self.gridLayout_15.addWidget(self.leT0Year_DataPreparationInputSectionDataInput, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gbDataInput)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_15.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gbDataInput)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_15.addWidget(self.label, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gbDataInput)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_15.addWidget(self.label_24, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gbDataInput)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_15.addWidget(self.label_4, 0, 3, 1, 1)
        self.pbConvert_T1_DataPreparationInputSectionDataInput = QtWidgets.QPushButton(self.gbDataInput)
        self.pbConvert_T1_DataPreparationInputSectionDataInput.setEnabled(False)
        self.pbConvert_T1_DataPreparationInputSectionDataInput.setObjectName("pbConvert_T1_DataPreparationInputSectionDataInput")
        self.gridLayout_15.addWidget(self.pbConvert_T1_DataPreparationInputSectionDataInput, 1, 5, 1, 1)
        self.pbSelectFileAreaOfInterest_DataPreparationInputSectionDataInput = QtWidgets.QPushButton(self.gbDataInput)
        self.pbSelectFileAreaOfInterest_DataPreparationInputSectionDataInput.setObjectName("pbSelectFileAreaOfInterest_DataPreparationInputSectionDataInput")
        self.gridLayout_15.addWidget(self.pbSelectFileAreaOfInterest_DataPreparationInputSectionDataInput, 2, 2, 1, 1)
        self.pbConvert_T0_DataPreparationInputSectionDataInput = QtWidgets.QPushButton(self.gbDataInput)
        self.pbConvert_T0_DataPreparationInputSectionDataInput.setEnabled(False)
        self.pbConvert_T0_DataPreparationInputSectionDataInput.setObjectName("pbConvert_T0_DataPreparationInputSectionDataInput")
        self.gridLayout_15.addWidget(self.pbConvert_T0_DataPreparationInputSectionDataInput, 0, 5, 1, 1)
        self.pbSelectFileT1File_DataPreparationInputSelectionDataInput = QtWidgets.QPushButton(self.gbDataInput)
        self.pbSelectFileT1File_DataPreparationInputSelectionDataInput.setObjectName("pbSelectFileT1File_DataPreparationInputSelectionDataInput")
        self.gridLayout_15.addWidget(self.pbSelectFileT1File_DataPreparationInputSelectionDataInput, 1, 2, 1, 1)
        self.leT1File_DataPreparationInputSectionDataInput = QtWidgets.QLineEdit(self.gbDataInput)
        self.leT1File_DataPreparationInputSectionDataInput.setEnabled(True)
        self.leT1File_DataPreparationInputSectionDataInput.setText("")
        self.leT1File_DataPreparationInputSectionDataInput.setObjectName("leT1File_DataPreparationInputSectionDataInput")
        self.gridLayout_15.addWidget(self.leT1File_DataPreparationInputSectionDataInput, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gbDataInput)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_15.addWidget(self.label_10, 2, 0, 1, 1)
        self.leMask_DataPreparationInputSectionDataInput = QtWidgets.QLineEdit(self.gbDataInput)
        self.leMask_DataPreparationInputSectionDataInput.setObjectName("leMask_DataPreparationInputSectionDataInput")
        self.gridLayout_15.addWidget(self.leMask_DataPreparationInputSectionDataInput, 2, 4, 1, 1)
        self.pbSelectFileMask_DataPreparationInputSectionDataInput = QtWidgets.QPushButton(self.gbDataInput)
        self.pbSelectFileMask_DataPreparationInputSectionDataInput.setObjectName("pbSelectFileMask_DataPreparationInputSectionDataInput")
        self.gridLayout_15.addWidget(self.pbSelectFileMask_DataPreparationInputSectionDataInput, 2, 5, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.gbDataInput, 1, 0, 1, 1)
        self.gbOutputSection = QtWidgets.QGroupBox(self.groupBox_4)
        self.gbOutputSection.setObjectName("gbOutputSection")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gbOutputSection)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.leOutputFile_DataPreparationOutputSection = QtWidgets.QLineEdit(self.gbOutputSection)
        self.leOutputFile_DataPreparationOutputSection.setEnabled(True)
        self.leOutputFile_DataPreparationOutputSection.setText("")
        self.leOutputFile_DataPreparationOutputSection.setObjectName("leOutputFile_DataPreparationOutputSection")
        self.gridLayout_35.addWidget(self.leOutputFile_DataPreparationOutputSection, 0, 0, 1, 1)
        self.pbSelectFileOutputFile_DataPreparationOutputSection = QtWidgets.QPushButton(self.gbOutputSection)
        self.pbSelectFileOutputFile_DataPreparationOutputSection.setObjectName("pbSelectFileOutputFile_DataPreparationOutputSection")
        self.gridLayout_35.addWidget(self.pbSelectFileOutputFile_DataPreparationOutputSection, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_35, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gbOutputSection)
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.gbOutputSection, 2, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 2, 2, 3, 2)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.textBrowser = QtWidgets.QTextBrowser(self.tabDataPreparation)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_33.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tabDataPreparation)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/images/images/Allinone.jpeg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_33.addWidget(self.label_12, 0, 0, 1, 3)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tabDataPreparation)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_33.addWidget(self.textBrowser_2, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tabDataPreparation)
        self.label_13.setAutoFillBackground(True)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/images/images/icon.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_33.addWidget(self.label_13, 1, 2, 1, 1)
        self.pbNextDataPreparation = QtWidgets.QPushButton(self.tabDataPreparation)
        self.pbNextDataPreparation.setEnabled(False)
        self.pbNextDataPreparation.setObjectName("pbNextDataPreparation")
        self.gridLayout_33.addWidget(self.pbNextDataPreparation, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem, 2, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_33, 3, 0, 1, 2)
        self.tabWidget.addTab(self.tabDataPreparation, "")
        self.tabDriverSelectionT0 = QtWidgets.QWidget()
        self.tabDriverSelectionT0.setEnabled(True)
        self.tabDriverSelectionT0.setObjectName("tabDriverSelectionT0")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.tabDriverSelectionT0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem1, 1, 0, 1, 1)
        self.pbNext_DriverSelectionT0 = QtWidgets.QPushButton(self.tabDriverSelectionT0)
        self.pbNext_DriverSelectionT0.setEnabled(False)
        self.pbNext_DriverSelectionT0.setObjectName("pbNext_DriverSelectionT0")
        self.gridLayout_24.addWidget(self.pbNext_DriverSelectionT0, 1, 1, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gbDoModelFitting_DriverSelectionT0 = QtWidgets.QGroupBox(self.tabDriverSelectionT0)
        self.gbDoModelFitting_DriverSelectionT0.setEnabled(False)
        self.gbDoModelFitting_DriverSelectionT0.setObjectName("gbDoModelFitting_DriverSelectionT0")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.gbDoModelFitting_DriverSelectionT0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.gbDoModelFitting_DriverSelectionT0)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.teModelparameterOutput_DriverSelectionT0DoModelFitting = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.teModelparameterOutput_DriverSelectionT0DoModelFitting.setEnabled(False)
        self.teModelparameterOutput_DriverSelectionT0DoModelFitting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.teModelparameterOutput_DriverSelectionT0DoModelFitting.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.teModelparameterOutput_DriverSelectionT0DoModelFitting.setReadOnly(True)
        self.teModelparameterOutput_DriverSelectionT0DoModelFitting.setObjectName("teModelparameterOutput_DriverSelectionT0DoModelFitting")
        self.gridLayout_20.addWidget(self.teModelparameterOutput_DriverSelectionT0DoModelFitting, 0, 0, 1, 2)
        self.gridLayout_9.addWidget(self.groupBox_3, 2, 0, 2, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.rbLinearRegression_DriverSelectionT0DoModelFitting = QtWidgets.QRadioButton(self.gbDoModelFitting_DriverSelectionT0)
        self.rbLinearRegression_DriverSelectionT0DoModelFitting.setObjectName("rbLinearRegression_DriverSelectionT0DoModelFitting")
        self.gridLayout_8.addWidget(self.rbLinearRegression_DriverSelectionT0DoModelFitting, 1, 1, 1, 1)
        self.rbNeuralregression_DriverSelectionT0DoModelFitting = QtWidgets.QRadioButton(self.gbDoModelFitting_DriverSelectionT0)
        self.rbNeuralregression_DriverSelectionT0DoModelFitting.setObjectName("rbNeuralregression_DriverSelectionT0DoModelFitting")
        self.gridLayout_8.addWidget(self.rbNeuralregression_DriverSelectionT0DoModelFitting, 1, 2, 1, 1)
        self.pbViewModelStatistics_DriverSelectionT0DoModelFitting = QtWidgets.QPushButton(self.gbDoModelFitting_DriverSelectionT0)
        self.pbViewModelStatistics_DriverSelectionT0DoModelFitting.setEnabled(False)
        self.pbViewModelStatistics_DriverSelectionT0DoModelFitting.setObjectName("pbViewModelStatistics_DriverSelectionT0DoModelFitting")
        self.gridLayout_8.addWidget(self.pbViewModelStatistics_DriverSelectionT0DoModelFitting, 1, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 1, 4, 1, 1)
        self.rbLogisticRegression_DriverSelectionT0DoModelFitting = QtWidgets.QRadioButton(self.gbDoModelFitting_DriverSelectionT0)
        self.rbLogisticRegression_DriverSelectionT0DoModelFitting.setObjectName("rbLogisticRegression_DriverSelectionT0DoModelFitting")
        self.gridLayout_8.addWidget(self.rbLogisticRegression_DriverSelectionT0DoModelFitting, 1, 0, 1, 1)
        self.rbRandomForest_DriverSelectionT0DoModelFitting = QtWidgets.QRadioButton(self.gbDoModelFitting_DriverSelectionT0)
        self.rbRandomForest_DriverSelectionT0DoModelFitting.setObjectName("rbRandomForest_DriverSelectionT0DoModelFitting")
        self.gridLayout_8.addWidget(self.rbRandomForest_DriverSelectionT0DoModelFitting, 1, 3, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.gbDoModelFitting_DriverSelectionT0, 1, 0, 1, 1)
        self.gbSelectDrivers_DriverSelectionT0 = QtWidgets.QGroupBox(self.tabDriverSelectionT0)
        self.gbSelectDrivers_DriverSelectionT0.setEnabled(False)
        self.gbSelectDrivers_DriverSelectionT0.setMinimumSize(QtCore.QSize(4, 3))
        self.gbSelectDrivers_DriverSelectionT0.setObjectName("gbSelectDrivers_DriverSelectionT0")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.gbSelectDrivers_DriverSelectionT0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.pbAddDriver_DriverSelectionT0SelectDrivers = QtWidgets.QPushButton(self.gbSelectDrivers_DriverSelectionT0)
        self.pbAddDriver_DriverSelectionT0SelectDrivers.setEnabled(False)
        self.pbAddDriver_DriverSelectionT0SelectDrivers.setObjectName("pbAddDriver_DriverSelectionT0SelectDrivers")
        self.gridLayout_23.addWidget(self.pbAddDriver_DriverSelectionT0SelectDrivers, 0, 0, 1, 1)
        self.twSelectDrivers_DriverSelectionT0 = QtWidgets.QTableWidget(self.gbSelectDrivers_DriverSelectionT0)
        self.twSelectDrivers_DriverSelectionT0.setEnabled(False)
        self.twSelectDrivers_DriverSelectionT0.setWordWrap(False)
        self.twSelectDrivers_DriverSelectionT0.setRowCount(0)
        self.twSelectDrivers_DriverSelectionT0.setObjectName("twSelectDrivers_DriverSelectionT0")
        self.twSelectDrivers_DriverSelectionT0.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.twSelectDrivers_DriverSelectionT0.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twSelectDrivers_DriverSelectionT0.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twSelectDrivers_DriverSelectionT0.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twSelectDrivers_DriverSelectionT0.setHorizontalHeaderItem(3, item)
        self.twSelectDrivers_DriverSelectionT0.horizontalHeader().setCascadingSectionResizes(True)
        self.twSelectDrivers_DriverSelectionT0.horizontalHeader().setDefaultSectionSize(100)
        self.gridLayout_23.addWidget(self.twSelectDrivers_DriverSelectionT0, 1, 0, 1, 1)
        self.gridLayout_22.addWidget(self.gbSelectDrivers_DriverSelectionT0, 0, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_22, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tabDriverSelectionT0, "")
        self.tabModelAnalysis = QtWidgets.QWidget()
        self.tabModelAnalysis.setObjectName("tabModelAnalysis")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.tabModelAnalysis)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gbViewModelCoefficient_ModelAnalysis = QtWidgets.QGroupBox(self.tabModelAnalysis)
        self.gbViewModelCoefficient_ModelAnalysis.setEnabled(False)
        self.gbViewModelCoefficient_ModelAnalysis.setMinimumSize(QtCore.QSize(4, 3))
        self.gbViewModelCoefficient_ModelAnalysis.setObjectName("gbViewModelCoefficient_ModelAnalysis")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbViewModelCoefficient_ModelAnalysis)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rbLogisiticRegression_ModelAnalysisViewModelCoeeffcient = QtWidgets.QRadioButton(self.gbViewModelCoefficient_ModelAnalysis)
        self.rbLogisiticRegression_ModelAnalysisViewModelCoeeffcient.setObjectName("rbLogisiticRegression_ModelAnalysisViewModelCoeeffcient")
        self.gridLayout_4.addWidget(self.rbLogisiticRegression_ModelAnalysisViewModelCoeeffcient, 0, 0, 1, 1)
        self.rbNeuralRegression_ModelAnalysisViewModelCoeeffcient = QtWidgets.QRadioButton(self.gbViewModelCoefficient_ModelAnalysis)
        self.rbNeuralRegression_ModelAnalysisViewModelCoeeffcient.setObjectName("rbNeuralRegression_ModelAnalysisViewModelCoeeffcient")
        self.gridLayout_4.addWidget(self.rbNeuralRegression_ModelAnalysisViewModelCoeeffcient, 0, 2, 1, 1)
        self.rbLinearRegression_ModelAnalysisViewModelCoeeffcient = QtWidgets.QRadioButton(self.gbViewModelCoefficient_ModelAnalysis)
        self.rbLinearRegression_ModelAnalysisViewModelCoeeffcient.setObjectName("rbLinearRegression_ModelAnalysisViewModelCoeeffcient")
        self.gridLayout_4.addWidget(self.rbLinearRegression_ModelAnalysisViewModelCoeeffcient, 0, 1, 1, 1)
        self.twViewModelCoefficint_ModelAnalysis = QtWidgets.QTableWidget(self.gbViewModelCoefficient_ModelAnalysis)
        self.twViewModelCoefficint_ModelAnalysis.setObjectName("twViewModelCoefficint_ModelAnalysis")
        self.twViewModelCoefficint_ModelAnalysis.setColumnCount(0)
        self.twViewModelCoefficint_ModelAnalysis.setRowCount(0)
        self.gridLayout_4.addWidget(self.twViewModelCoefficint_ModelAnalysis, 1, 0, 1, 5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 4, 1, 1)
        self.rbRandomForest_ModelAnalysisViewModelCoeeffcient = QtWidgets.QRadioButton(self.gbViewModelCoefficient_ModelAnalysis)
        self.rbRandomForest_ModelAnalysisViewModelCoeeffcient.setObjectName("rbRandomForest_ModelAnalysisViewModelCoeeffcient")
        self.gridLayout_4.addWidget(self.rbRandomForest_ModelAnalysisViewModelCoeeffcient, 0, 3, 1, 1)
        self.gridLayout_26.addWidget(self.gbViewModelCoefficient_ModelAnalysis, 0, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem4, 2, 0, 1, 1)
        self.pbNext_ModelAnalysis = QtWidgets.QPushButton(self.tabModelAnalysis)
        self.pbNext_ModelAnalysis.setEnabled(False)
        self.pbNext_ModelAnalysis.setObjectName("pbNext_ModelAnalysis")
        self.gridLayout_26.addWidget(self.pbNext_ModelAnalysis, 2, 1, 1, 1)
        self.gbMigrationOrder_ModelAnalysis = QtWidgets.QGroupBox(self.tabModelAnalysis)
        self.gbMigrationOrder_ModelAnalysis.setEnabled(False)
        self.gbMigrationOrder_ModelAnalysis.setObjectName("gbMigrationOrder_ModelAnalysis")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.gbMigrationOrder_ModelAnalysis)
        self.gridLayout_25.setObjectName("gridLayout_25")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem5, 0, 3, 1, 1)
        self.twMigrationOrder_ModelAnalysis = QtWidgets.QTableWidget(self.gbMigrationOrder_ModelAnalysis)
        self.twMigrationOrder_ModelAnalysis.setObjectName("twMigrationOrder_ModelAnalysis")
        self.twMigrationOrder_ModelAnalysis.setColumnCount(0)
        self.twMigrationOrder_ModelAnalysis.setRowCount(0)
        self.gridLayout_25.addWidget(self.twMigrationOrder_ModelAnalysis, 1, 0, 1, 4)
        self.rbUserDefined_ModelAnalysisMigrationOrder = QtWidgets.QRadioButton(self.gbMigrationOrder_ModelAnalysis)
        self.rbUserDefined_ModelAnalysisMigrationOrder.setObjectName("rbUserDefined_ModelAnalysisMigrationOrder")
        self.gridLayout_25.addWidget(self.rbUserDefined_ModelAnalysisMigrationOrder, 0, 2, 1, 1)
        self.rbAuto_ModelAnalysisMigrationOrder = QtWidgets.QRadioButton(self.gbMigrationOrder_ModelAnalysis)
        self.rbAuto_ModelAnalysisMigrationOrder.setChecked(True)
        self.rbAuto_ModelAnalysisMigrationOrder.setObjectName("rbAuto_ModelAnalysisMigrationOrder")
        self.gridLayout_25.addWidget(self.rbAuto_ModelAnalysisMigrationOrder, 0, 1, 1, 1)
        self.gridLayout_26.addWidget(self.gbMigrationOrder_ModelAnalysis, 1, 0, 1, 2)
        self.gbMigrationOrder_ModelAnalysis.raise_()
        self.gbViewModelCoefficient_ModelAnalysis.raise_()
        self.pbNext_ModelAnalysis.raise_()
        self.tabWidget.addTab(self.tabModelAnalysis, "")
        self.tabDriverSelectionT1 = QtWidgets.QWidget()
        self.tabDriverSelectionT1.setObjectName("tabDriverSelectionT1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabDriverSelectionT1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 0, 1, 1)
        self.pbNext_DriverSelectionT1 = QtWidgets.QPushButton(self.tabDriverSelectionT1)
        self.pbNext_DriverSelectionT1.setEnabled(False)
        self.pbNext_DriverSelectionT1.setObjectName("pbNext_DriverSelectionT1")
        self.gridLayout_3.addWidget(self.pbNext_DriverSelectionT1, 1, 1, 1, 1)
        self.gbSelectModelTypeAndDrivers_DriverSelectionT1 = QtWidgets.QGroupBox(self.tabDriverSelectionT1)
        self.gbSelectModelTypeAndDrivers_DriverSelectionT1.setEnabled(False)
        self.gbSelectModelTypeAndDrivers_DriverSelectionT1.setMinimumSize(QtCore.QSize(4, 3))
        self.gbSelectModelTypeAndDrivers_DriverSelectionT1.setObjectName("gbSelectModelTypeAndDrivers_DriverSelectionT1")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.gbSelectModelTypeAndDrivers_DriverSelectionT1)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.rbLogisiticRegression_DriverSelectionT1SelectModelTypeAndDrivers = QtWidgets.QRadioButton(self.gbSelectModelTypeAndDrivers_DriverSelectionT1)
        self.rbLogisiticRegression_DriverSelectionT1SelectModelTypeAndDrivers.setObjectName("rbLogisiticRegression_DriverSelectionT1SelectModelTypeAndDrivers")
        self.gridLayout_30.addWidget(self.rbLogisiticRegression_DriverSelectionT1SelectModelTypeAndDrivers, 0, 1, 1, 1)
        self.rbNeuralRegression_DriverSelectionT1SelectModelTypeAndDrivers = QtWidgets.QRadioButton(self.gbSelectModelTypeAndDrivers_DriverSelectionT1)
        self.rbNeuralRegression_DriverSelectionT1SelectModelTypeAndDrivers.setObjectName("rbNeuralRegression_DriverSelectionT1SelectModelTypeAndDrivers")
        self.gridLayout_30.addWidget(self.rbNeuralRegression_DriverSelectionT1SelectModelTypeAndDrivers, 0, 3, 1, 1)
        self.rbIndvidualSelection_DriverSelectionT1SelectModelTypeAndDrivers = QtWidgets.QRadioButton(self.gbSelectModelTypeAndDrivers_DriverSelectionT1)
        self.rbIndvidualSelection_DriverSelectionT1SelectModelTypeAndDrivers.setObjectName("rbIndvidualSelection_DriverSelectionT1SelectModelTypeAndDrivers")
        self.gridLayout_30.addWidget(self.rbIndvidualSelection_DriverSelectionT1SelectModelTypeAndDrivers, 0, 5, 1, 1)
        self.rbLinearRegression_DriverSelectionT1SelectModelTypeAndDrivers = QtWidgets.QRadioButton(self.gbSelectModelTypeAndDrivers_DriverSelectionT1)
        self.rbLinearRegression_DriverSelectionT1SelectModelTypeAndDrivers.setObjectName("rbLinearRegression_DriverSelectionT1SelectModelTypeAndDrivers")
        self.gridLayout_30.addWidget(self.rbLinearRegression_DriverSelectionT1SelectModelTypeAndDrivers, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem7, 0, 6, 1, 1)
        self.twSelectModelTypeAndDrivers_DriverSelectionT1 = QtWidgets.QTableWidget(self.gbSelectModelTypeAndDrivers_DriverSelectionT1)
        self.twSelectModelTypeAndDrivers_DriverSelectionT1.setEnabled(False)
        self.twSelectModelTypeAndDrivers_DriverSelectionT1.setObjectName("twSelectModelTypeAndDrivers_DriverSelectionT1")
        self.twSelectModelTypeAndDrivers_DriverSelectionT1.setColumnCount(0)
        self.twSelectModelTypeAndDrivers_DriverSelectionT1.setRowCount(0)
        self.gridLayout_30.addWidget(self.twSelectModelTypeAndDrivers_DriverSelectionT1, 4, 0, 1, 7)
        self.rbRandomForest_DriverSelectionT1SelectModelTypeAndDrivers = QtWidgets.QRadioButton(self.gbSelectModelTypeAndDrivers_DriverSelectionT1)
        self.rbRandomForest_DriverSelectionT1SelectModelTypeAndDrivers.setObjectName("rbRandomForest_DriverSelectionT1SelectModelTypeAndDrivers")
        self.gridLayout_30.addWidget(self.rbRandomForest_DriverSelectionT1SelectModelTypeAndDrivers, 0, 4, 1, 1)
        self.gridLayout_3.addWidget(self.gbSelectModelTypeAndDrivers_DriverSelectionT1, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tabDriverSelectionT1, "")
        self.tabDemandAllocation = QtWidgets.QWidget()
        self.tabDemandAllocation.setObjectName("tabDemandAllocation")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.tabDemandAllocation)
        self.gridLayout_27.setObjectName("gridLayout_27")
        spacerItem8 = QtWidgets.QSpacerItem(897, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem8, 2, 0, 1, 1)
        self.pbExecute_DemandAllocation = QtWidgets.QPushButton(self.tabDemandAllocation)
        self.pbExecute_DemandAllocation.setEnabled(False)
        self.pbExecute_DemandAllocation.setObjectName("pbExecute_DemandAllocation")
        self.gridLayout_27.addWidget(self.pbExecute_DemandAllocation, 2, 1, 1, 1)
        self.gbPolicies = QtWidgets.QGroupBox(self.tabDemandAllocation)
        self.gbPolicies.setEnabled(False)
        self.gbPolicies.setMinimumSize(QtCore.QSize(4, 3))
        self.gbPolicies.setObjectName("gbPolicies")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.gbPolicies)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gbSpatialContext = QtWidgets.QGroupBox(self.gbPolicies)
        self.gbSpatialContext.setEnabled(False)
        self.gbSpatialContext.setObjectName("gbSpatialContext")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.gbSpatialContext)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.cbInSteps_DemandAllocationSpatialContext = QtWidgets.QComboBox(self.gbSpatialContext)
        self.cbInSteps_DemandAllocationSpatialContext.setEnabled(False)
        self.cbInSteps_DemandAllocationSpatialContext.setObjectName("cbInSteps_DemandAllocationSpatialContext")
        self.cbInSteps_DemandAllocationSpatialContext.addItem("")
        self.gridLayout_29.addWidget(self.cbInSteps_DemandAllocationSpatialContext, 2, 5, 1, 1)
        self.lbInSteps = QtWidgets.QLabel(self.gbSpatialContext)
        self.lbInSteps.setEnabled(False)
        self.lbInSteps.setObjectName("lbInSteps")
        self.gridLayout_29.addWidget(self.lbInSteps, 2, 3, 1, 1)
        self.lbStepOutputRequired = QtWidgets.QLabel(self.gbSpatialContext)
        self.lbStepOutputRequired.setEnabled(False)
        self.lbStepOutputRequired.setObjectName("lbStepOutputRequired")
        self.gridLayout_29.addWidget(self.lbStepOutputRequired, 3, 0, 1, 1)
        self.cbStepOutputRequired_DemandAllocationSpatilaContext = QtWidgets.QComboBox(self.gbSpatialContext)
        self.cbStepOutputRequired_DemandAllocationSpatilaContext.setEnabled(False)
        self.cbStepOutputRequired_DemandAllocationSpatilaContext.setObjectName("cbStepOutputRequired_DemandAllocationSpatilaContext")
        self.cbStepOutputRequired_DemandAllocationSpatilaContext.addItem("")
        self.cbStepOutputRequired_DemandAllocationSpatilaContext.addItem("")
        self.gridLayout_29.addWidget(self.cbStepOutputRequired_DemandAllocationSpatilaContext, 3, 1, 1, 1)
        self.cbEnable_DemandAllocationSpatialContext = QtWidgets.QCheckBox(self.gbSpatialContext)
        self.cbEnable_DemandAllocationSpatialContext.setObjectName("cbEnable_DemandAllocationSpatialContext")
        self.gridLayout_29.addWidget(self.cbEnable_DemandAllocationSpatialContext, 0, 0, 1, 1)
        self.lbWindowSize = QtWidgets.QLabel(self.gbSpatialContext)
        self.lbWindowSize.setEnabled(False)
        self.lbWindowSize.setObjectName("lbWindowSize")
        self.gridLayout_29.addWidget(self.lbWindowSize, 2, 0, 1, 1)
        self.cbWindowSize_DemandAllocationSpatialContext = QtWidgets.QComboBox(self.gbSpatialContext)
        self.cbWindowSize_DemandAllocationSpatialContext.setEnabled(False)
        self.cbWindowSize_DemandAllocationSpatialContext.setObjectName("cbWindowSize_DemandAllocationSpatialContext")
        self.cbWindowSize_DemandAllocationSpatialContext.addItem("")
        self.cbWindowSize_DemandAllocationSpatialContext.addItem("")
        self.cbWindowSize_DemandAllocationSpatialContext.addItem("")
        self.gridLayout_29.addWidget(self.cbWindowSize_DemandAllocationSpatialContext, 2, 1, 1, 1)
        self.gridLayout_28.addWidget(self.gbSpatialContext, 3, 0, 1, 1)
        self.twPolicies_DemandAllocation = QtWidgets.QTableWidget(self.gbPolicies)
        self.twPolicies_DemandAllocation.setWordWrap(False)
        self.twPolicies_DemandAllocation.setObjectName("twPolicies_DemandAllocation")
        self.twPolicies_DemandAllocation.setColumnCount(0)
        self.twPolicies_DemandAllocation.setRowCount(0)
        self.gridLayout_28.addWidget(self.twPolicies_DemandAllocation, 2, 0, 1, 4)
        self.cbUserDefinedClassInertia_DemandAllocation = QtWidgets.QCheckBox(self.gbPolicies)
        self.cbUserDefinedClassInertia_DemandAllocation.setObjectName("cbUserDefinedClassInertia_DemandAllocation")
        self.gridLayout_28.addWidget(self.cbUserDefinedClassInertia_DemandAllocation, 1, 0, 1, 1)
        self.cbUserDefinedDemand_DemandAllocation = QtWidgets.QCheckBox(self.gbPolicies)
        self.cbUserDefinedDemand_DemandAllocation.setObjectName("cbUserDefinedDemand_DemandAllocation")
        self.gridLayout_28.addWidget(self.cbUserDefinedDemand_DemandAllocation, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem9, 0, 2, 1, 1)
        self.gbSuitabilityMapGeneration = QtWidgets.QGroupBox(self.gbPolicies)
        self.gbSuitabilityMapGeneration.setObjectName("gbSuitabilityMapGeneration")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.gbSuitabilityMapGeneration)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.lbSuitablityfile = QtWidgets.QLabel(self.gbSuitabilityMapGeneration)
        self.lbSuitablityfile.setObjectName("lbSuitablityfile")
        self.gridLayout_32.addWidget(self.lbSuitablityfile, 1, 0, 1, 1)
        self.leSuitablityFile_OutputGenerationSuitabilityMapGeneration = QtWidgets.QLineEdit(self.gbSuitabilityMapGeneration)
        self.leSuitablityFile_OutputGenerationSuitabilityMapGeneration.setObjectName("leSuitablityFile_OutputGenerationSuitabilityMapGeneration")
        self.gridLayout_32.addWidget(self.leSuitablityFile_OutputGenerationSuitabilityMapGeneration, 1, 1, 1, 1)
        self.pbSelectFileSuitablityFile_OutputGenerationSuitabilityMapGeneration = QtWidgets.QPushButton(self.gbSuitabilityMapGeneration)
        self.pbSelectFileSuitablityFile_OutputGenerationSuitabilityMapGeneration.setObjectName("pbSelectFileSuitablityFile_OutputGenerationSuitabilityMapGeneration")
        self.gridLayout_32.addWidget(self.pbSelectFileSuitablityFile_OutputGenerationSuitabilityMapGeneration, 1, 2, 1, 1)
        self.cbEnable_SuitabilityMapGeneration = QtWidgets.QCheckBox(self.gbSuitabilityMapGeneration)
        self.cbEnable_SuitabilityMapGeneration.setObjectName("cbEnable_SuitabilityMapGeneration")
        self.gridLayout_32.addWidget(self.cbEnable_SuitabilityMapGeneration, 0, 0, 1, 1)
        self.gridLayout_28.addWidget(self.gbSuitabilityMapGeneration, 3, 1, 1, 2)
        self.cbclassallocation_DemandAllocation = QtWidgets.QCheckBox(self.gbPolicies)
        self.cbclassallocation_DemandAllocation.setObjectName("cbclassallocation_DemandAllocation")
        self.gridLayout_28.addWidget(self.cbclassallocation_DemandAllocation, 0, 1, 1, 1)
        self.gridLayout_27.addWidget(self.gbPolicies, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tabDemandAllocation, "")
        self.tabAccuracyAssesment = QtWidgets.QWidget()
        self.tabAccuracyAssesment.setObjectName("tabAccuracyAssesment")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tabAccuracyAssesment)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gbDetailed_AccuracyAssesment = QtWidgets.QGroupBox(self.tabAccuracyAssesment)
        self.gbDetailed_AccuracyAssesment.setEnabled(False)
        self.gbDetailed_AccuracyAssesment.setObjectName("gbDetailed_AccuracyAssesment")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gbDetailed_AccuracyAssesment)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.rbPreditedMapAccuracy_AccuracyAssesmentDetailed = QtWidgets.QRadioButton(self.gbDetailed_AccuracyAssesment)
        self.rbPreditedMapAccuracy_AccuracyAssesmentDetailed.setObjectName("rbPreditedMapAccuracy_AccuracyAssesmentDetailed")
        self.gridLayout_6.addWidget(self.rbPreditedMapAccuracy_AccuracyAssesmentDetailed, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem10, 0, 4, 1, 1)
        self.rbReferenceMapReliablity_AccuracyAssesmentDetailed = QtWidgets.QRadioButton(self.gbDetailed_AccuracyAssesment)
        self.rbReferenceMapReliablity_AccuracyAssesmentDetailed.setObjectName("rbReferenceMapReliablity_AccuracyAssesmentDetailed")
        self.gridLayout_6.addWidget(self.rbReferenceMapReliablity_AccuracyAssesmentDetailed, 0, 3, 1, 1)
        self.rbConfusionMatrix_AccuracyAssesmentDetailed = QtWidgets.QRadioButton(self.gbDetailed_AccuracyAssesment)
        self.rbConfusionMatrix_AccuracyAssesmentDetailed.setObjectName("rbConfusionMatrix_AccuracyAssesmentDetailed")
        self.gridLayout_6.addWidget(self.rbConfusionMatrix_AccuracyAssesmentDetailed, 0, 0, 1, 1)
        self.twDetailed_AccuracyAssesment = QtWidgets.QTableWidget(self.gbDetailed_AccuracyAssesment)
        self.twDetailed_AccuracyAssesment.setObjectName("twDetailed_AccuracyAssesment")
        self.twDetailed_AccuracyAssesment.setColumnCount(0)
        self.twDetailed_AccuracyAssesment.setRowCount(0)
        self.gridLayout_6.addWidget(self.twDetailed_AccuracyAssesment, 2, 0, 1, 5)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem11, 1, 0, 1, 5)
        self.gridLayout_12.addWidget(self.gbDetailed_AccuracyAssesment, 2, 0, 1, 6)
        self.gbSummary_AccuracyAssesment = QtWidgets.QGroupBox(self.tabAccuracyAssesment)
        self.gbSummary_AccuracyAssesment.setEnabled(True)
        self.gbSummary_AccuracyAssesment.setObjectName("gbSummary_AccuracyAssesment")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gbSummary_AccuracyAssesment)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pbFindAccuracy_AccuracyAssesment = QtWidgets.QPushButton(self.gbSummary_AccuracyAssesment)
        self.pbFindAccuracy_AccuracyAssesment.setEnabled(True)
        self.pbFindAccuracy_AccuracyAssesment.setObjectName("pbFindAccuracy_AccuracyAssesment")
        self.gridLayout_11.addWidget(self.pbFindAccuracy_AccuracyAssesment, 2, 7, 1, 1)
        self.pbSelectFileActualFile_AccuracyAssesment = QtWidgets.QPushButton(self.gbSummary_AccuracyAssesment)
        self.pbSelectFileActualFile_AccuracyAssesment.setEnabled(True)
        self.pbSelectFileActualFile_AccuracyAssesment.setObjectName("pbSelectFileActualFile_AccuracyAssesment")
        self.gridLayout_11.addWidget(self.pbSelectFileActualFile_AccuracyAssesment, 1, 7, 1, 1)
        self.pbSelectFilePredictedFile_AccuracyAssesment = QtWidgets.QPushButton(self.gbSummary_AccuracyAssesment)
        self.pbSelectFilePredictedFile_AccuracyAssesment.setEnabled(True)
        self.pbSelectFilePredictedFile_AccuracyAssesment.setObjectName("pbSelectFilePredictedFile_AccuracyAssesment")
        self.gridLayout_11.addWidget(self.pbSelectFilePredictedFile_AccuracyAssesment, 0, 7, 1, 1)
        self.leActualFile_AccuracyAssesment = QtWidgets.QLineEdit(self.gbSummary_AccuracyAssesment)
        self.leActualFile_AccuracyAssesment.setEnabled(True)
        self.leActualFile_AccuracyAssesment.setObjectName("leActualFile_AccuracyAssesment")
        self.gridLayout_11.addWidget(self.leActualFile_AccuracyAssesment, 1, 1, 1, 6)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem12, 2, 1, 1, 6)
        self.gbSummarStats_AccuracyAssesementSummary = QtWidgets.QGroupBox(self.gbSummary_AccuracyAssesment)
        self.gbSummarStats_AccuracyAssesementSummary.setEnabled(False)
        self.gbSummarStats_AccuracyAssesementSummary.setTitle("")
        self.gbSummarStats_AccuracyAssesementSummary.setObjectName("gbSummarStats_AccuracyAssesementSummary")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gbSummarStats_AccuracyAssesementSummary)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_19 = QtWidgets.QLabel(self.gbSummarStats_AccuracyAssesementSummary)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 0, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gbSummarStats_AccuracyAssesementSummary)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gbSummarStats_AccuracyAssesementSummary)
        self.label_17.setMouseTracking(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 1, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gbSummarStats_AccuracyAssesementSummary)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gbSummarStats_AccuracyAssesementSummary)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gbSummarStats_AccuracyAssesementSummary)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 2, 0, 1, 1)
        self.leOverallKappa_AccuracyAssesment = QtWidgets.QLineEdit(self.gbSummarStats_AccuracyAssesementSummary)
        self.leOverallKappa_AccuracyAssesment.setObjectName("leOverallKappa_AccuracyAssesment")
        self.gridLayout_7.addWidget(self.leOverallKappa_AccuracyAssesment, 0, 1, 1, 1)
        self.leOverallKappaCI_AccuracyAssesment95 = QtWidgets.QLineEdit(self.gbSummarStats_AccuracyAssesementSummary)
        self.leOverallKappaCI_AccuracyAssesment95.setObjectName("leOverallKappaCI_AccuracyAssesment95")
        self.gridLayout_7.addWidget(self.leOverallKappaCI_AccuracyAssesment95, 0, 3, 1, 1)
        self.leOverallAccuracy_AccuracyAssesment = QtWidgets.QLineEdit(self.gbSummarStats_AccuracyAssesementSummary)
        self.leOverallAccuracy_AccuracyAssesment.setObjectName("leOverallAccuracy_AccuracyAssesment")
        self.gridLayout_7.addWidget(self.leOverallAccuracy_AccuracyAssesment, 1, 1, 1, 1)
        self.leOverallAccuracyCI_AccuracyAssesment95 = QtWidgets.QLineEdit(self.gbSummarStats_AccuracyAssesementSummary)
        self.leOverallAccuracyCI_AccuracyAssesment95.setObjectName("leOverallAccuracyCI_AccuracyAssesment95")
        self.gridLayout_7.addWidget(self.leOverallAccuracyCI_AccuracyAssesment95, 1, 3, 1, 1)
        self.leNoOfObservation_AccuracyAssesmentSummary = QtWidgets.QLineEdit(self.gbSummarStats_AccuracyAssesementSummary)
        self.leNoOfObservation_AccuracyAssesmentSummary.setObjectName("leNoOfObservation_AccuracyAssesmentSummary")
        self.gridLayout_7.addWidget(self.leNoOfObservation_AccuracyAssesmentSummary, 2, 1, 1, 1)
        self.leOverallKappaCI_AccuracyAssesment99 = QtWidgets.QLineEdit(self.gbSummarStats_AccuracyAssesementSummary)
        self.leOverallKappaCI_AccuracyAssesment99.setObjectName("leOverallKappaCI_AccuracyAssesment99")
        self.gridLayout_7.addWidget(self.leOverallKappaCI_AccuracyAssesment99, 0, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gbSummarStats_AccuracyAssesementSummary)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 1, 4, 1, 1)
        self.leOverallAccuracyCI_AccuracyAssesment99 = QtWidgets.QLineEdit(self.gbSummarStats_AccuracyAssesementSummary)
        self.leOverallAccuracyCI_AccuracyAssesment99.setObjectName("leOverallAccuracyCI_AccuracyAssesment99")
        self.gridLayout_7.addWidget(self.leOverallAccuracyCI_AccuracyAssesment99, 1, 5, 1, 1)
        self.gridLayout_11.addWidget(self.gbSummarStats_AccuracyAssesementSummary, 3, 0, 1, 8)
        self.label_14 = QtWidgets.QLabel(self.gbSummary_AccuracyAssesment)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lePredictedFile_AccuracyAssesment = QtWidgets.QLineEdit(self.gbSummary_AccuracyAssesment)
        self.lePredictedFile_AccuracyAssesment.setEnabled(True)
        self.lePredictedFile_AccuracyAssesment.setReadOnly(True)
        self.lePredictedFile_AccuracyAssesment.setObjectName("lePredictedFile_AccuracyAssesment")
        self.gridLayout_11.addWidget(self.lePredictedFile_AccuracyAssesment, 0, 1, 1, 6)
        self.label_11 = QtWidgets.QLabel(self.gbSummary_AccuracyAssesment)
        self.label_11.setObjectName("label_11")
        self.gridLayout_11.addWidget(self.label_11, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_12.addWidget(self.gbSummary_AccuracyAssesment, 0, 0, 1, 6)
        self.tabWidget.addTab(self.tabAccuracyAssesment, "")
        self.tabViewMaps = QtWidgets.QWidget()
        self.tabViewMaps.setObjectName("tabViewMaps")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.tabViewMaps)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.pbExport_ViewMaps = QtWidgets.QPushButton(self.tabViewMaps)
        self.pbExport_ViewMaps.setObjectName("pbExport_ViewMaps")
        self.gridLayout_31.addWidget(self.pbExport_ViewMaps, 0, 7, 1, 1)
        self.pbShow_ViewMaps = QtWidgets.QPushButton(self.tabViewMaps)
        self.pbShow_ViewMaps.setObjectName("pbShow_ViewMaps")
        self.gridLayout_31.addWidget(self.pbShow_ViewMaps, 0, 6, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tabViewMaps)
        self.label_23.setObjectName("label_23")
        self.gridLayout_31.addWidget(self.label_23, 0, 2, 1, 1)
        self.leTitle_ViewMaps = QtWidgets.QLineEdit(self.tabViewMaps)
        self.leTitle_ViewMaps.setObjectName("leTitle_ViewMaps")
        self.gridLayout_31.addWidget(self.leTitle_ViewMaps, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tabViewMaps)
        self.label_22.setObjectName("label_22")
        self.gridLayout_31.addWidget(self.label_22, 0, 0, 1, 1)
        self.leLegendHeading_ViewMaps = QtWidgets.QLineEdit(self.tabViewMaps)
        self.leLegendHeading_ViewMaps.setObjectName("leLegendHeading_ViewMaps")
        self.gridLayout_31.addWidget(self.leLegendHeading_ViewMaps, 0, 3, 1, 1)
        self.cbFile_ViewMaps = QtWidgets.QComboBox(self.tabViewMaps)
        self.cbFile_ViewMaps.setEditable(True)
        self.cbFile_ViewMaps.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.cbFile_ViewMaps.setObjectName("cbFile_ViewMaps")
        self.gridLayout_31.addWidget(self.cbFile_ViewMaps, 0, 4, 1, 2)
        self.lbCanvas_ViewMaps = QtWidgets.QLabel(self.tabViewMaps)
        self.lbCanvas_ViewMaps.setText("")
        self.lbCanvas_ViewMaps.setObjectName("lbCanvas_ViewMaps")
        self.gridLayout_31.addWidget(self.lbCanvas_ViewMaps, 1, 0, 1, 5)
        self.twColorTable_ViewMaps = QtWidgets.QTableWidget(self.tabViewMaps)
        self.twColorTable_ViewMaps.setObjectName("twColorTable_ViewMaps")
        self.twColorTable_ViewMaps.setColumnCount(0)
        self.twColorTable_ViewMaps.setRowCount(0)
        self.gridLayout_31.addWidget(self.twColorTable_ViewMaps, 1, 5, 1, 3)
        self.tabWidget.addTab(self.tabViewMaps, "")
        self.tabHelp = QtWidgets.QWidget()
        self.tabHelp.setObjectName("tabHelp")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.tabHelp)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.webView_Help = QtWebEngineWidgets.QWebEngineView(self.tabHelp)
        self.webView_Help.setProperty("url", QtCore.QUrl("about:blank"))
        self.webView_Help.setObjectName("webView_Help")
        self.gridLayout_36.addWidget(self.webView_Help, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabHelp, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximum(60)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        LULCModel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LULCModel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1005, 22))
        self.menubar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        LULCModel.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(LULCModel)
        self.statusBar.setAccessibleDescription("")
        self.statusBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusBar.setObjectName("statusBar")
        LULCModel.setStatusBar(self.statusBar)
        self.actionOpen_File = QtWidgets.QAction(LULCModel)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSave_File = QtWidgets.QAction(LULCModel)
        self.actionSave_File.setObjectName("actionSave_File")
        self.actionExit = QtWidgets.QAction(LULCModel)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionOpen_File)
        self.menuMenu.addAction(self.actionSave_File)
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(LULCModel)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LULCModel)

    def retranslateUi(self, LULCModel):
        _translate = QtCore.QCoreApplication.translate
        LULCModel.setWindowTitle(_translate("LULCModel", "MainWindow"))
        self.groupBox_4.setTitle(_translate("LULCModel", "Input Section"))
        self.gbProjectSection.setTitle(_translate("LULCModel", "Project Section"))
        self.leProjectDirectory_DataPreparationInputSectionProjectSection.setPlaceholderText(_translate("LULCModel", "Project Directory"))
        self.label_6.setText(_translate("LULCModel", "NA Value"))
        self.label_5.setText(_translate("LULCModel", " Project Directory: "))
        self.pbSelectDirectory_DataPreparationInputSectionProjectSection.setText(_translate("LULCModel", "Select Directory"))
        self.label_7.setText(_translate("LULCModel", "Gridsize: "))
        self.leNAValue_DataPreparationInputSectionProjectSection.setText(_translate("LULCModel", "128"))
        self.gbDataInput.setTitle(_translate("LULCModel", "Data Input"))
        self.leT0File_DataPreparationInputSectionDataInput.setPlaceholderText(_translate("LULCModel", "input T1.tif or T1.shp "))
        self.pbSelectFileT0File_DataPreparationInputSelectionDataInput.setText(_translate("LULCModel", "Select File"))
        self.label_3.setText(_translate("LULCModel", "Year (T2):"))
        self.leT1Year_DataPreparationInputSectionDataInput.setPlaceholderText(_translate("LULCModel", "1995"))
        self.leAreaOfInterest_DataPreparationInputSectionDataInput.setPlaceholderText(_translate("LULCModel", "AOI.tif or AOI.shp"))
        self.leT0Year_DataPreparationInputSectionDataInput.setPlaceholderText(_translate("LULCModel", "1985"))
        self.label_2.setText(_translate("LULCModel", "T2 File: "))
        self.label.setText(_translate("LULCModel", "T1 File: "))
        self.label_24.setText(_translate("LULCModel", "Mask:"))
        self.label_4.setText(_translate("LULCModel", "Year (T1):"))
        self.pbConvert_T1_DataPreparationInputSectionDataInput.setText(_translate("LULCModel", "Convert"))
        self.pbSelectFileAreaOfInterest_DataPreparationInputSectionDataInput.setText(_translate("LULCModel", "Select File"))
        self.pbConvert_T0_DataPreparationInputSectionDataInput.setText(_translate("LULCModel", "Convert"))
        self.pbSelectFileT1File_DataPreparationInputSelectionDataInput.setText(_translate("LULCModel", "Select File"))
        self.leT1File_DataPreparationInputSectionDataInput.setPlaceholderText(_translate("LULCModel", "input T2.tif or T2.shp "))
        self.label_10.setText(_translate("LULCModel", "Area of Interest: "))
        self.leMask_DataPreparationInputSectionDataInput.setPlaceholderText(_translate("LULCModel", "mask.tiff or mask.shp"))
        self.pbSelectFileMask_DataPreparationInputSectionDataInput.setText(_translate("LULCModel", "Select File"))
        self.gbOutputSection.setTitle(_translate("LULCModel", "Output Section"))
        self.leOutputFile_DataPreparationOutputSection.setPlaceholderText(_translate("LULCModel", "Output Raster File.tif"))
        self.pbSelectFileOutputFile_DataPreparationOutputSection.setText(_translate("LULCModel", "Select File"))
        self.label_9.setText(_translate("LULCModel", "  Output File (Year T3): "))
        self.textBrowser.setHtml(_translate("LULCModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Indian Institute of Remote Sensing (IIRS)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Indian Space Research Organisation</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Dehradun, INDIA</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("LULCModel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Open-source LULC Dynamics Modeling Platform (OpenLDM)- ver-1.0</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">Developed under the ISRO-Geosphere Biosphere Programme</span></p></body></html>"))
        self.pbNextDataPreparation.setText(_translate("LULCModel", "Next"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDataPreparation), _translate("LULCModel", "Data Preparation"))
        self.pbNext_DriverSelectionT0.setText(_translate("LULCModel", "Next"))
        self.gbDoModelFitting_DriverSelectionT0.setTitle(_translate("LULCModel", "Do Model Fitting"))
        self.groupBox_3.setTitle(_translate("LULCModel", "Model Parameter Output"))
        self.rbLinearRegression_DriverSelectionT0DoModelFitting.setText(_translate("LULCModel", "Linear Regression"))
        self.rbNeuralregression_DriverSelectionT0DoModelFitting.setText(_translate("LULCModel", "Neural Regression"))
        self.pbViewModelStatistics_DriverSelectionT0DoModelFitting.setText(_translate("LULCModel", "View Model Statistics"))
        self.rbLogisticRegression_DriverSelectionT0DoModelFitting.setText(_translate("LULCModel", "Logistic Regression"))
        self.rbRandomForest_DriverSelectionT0DoModelFitting.setText(_translate("LULCModel", "Random Forest"))
        self.gbSelectDrivers_DriverSelectionT0.setTitle(_translate("LULCModel", "Select Drivers"))
        self.pbAddDriver_DriverSelectionT0SelectDrivers.setText(_translate("LULCModel", "Add Driver "))
        self.twSelectDrivers_DriverSelectionT0.setSortingEnabled(False)
        item = self.twSelectDrivers_DriverSelectionT0.horizontalHeaderItem(0)
        item.setText(_translate("LULCModel", "Driver Name"))
        item = self.twSelectDrivers_DriverSelectionT0.horizontalHeaderItem(1)
        item.setText(_translate("LULCModel", "File Location"))
        item = self.twSelectDrivers_DriverSelectionT0.horizontalHeaderItem(2)
        item.setText(_translate("LULCModel", "Select Drivers"))
        item = self.twSelectDrivers_DriverSelectionT0.horizontalHeaderItem(3)
        item.setText(_translate("LULCModel", "Delete Drivers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDriverSelectionT0), _translate("LULCModel", "Driver Selection (T1)"))
        self.gbViewModelCoefficient_ModelAnalysis.setTitle(_translate("LULCModel", "View Model Coefficient"))
        self.rbLogisiticRegression_ModelAnalysisViewModelCoeeffcient.setText(_translate("LULCModel", "Logistic Regression"))
        self.rbNeuralRegression_ModelAnalysisViewModelCoeeffcient.setText(_translate("LULCModel", "Neural Regression"))
        self.rbLinearRegression_ModelAnalysisViewModelCoeeffcient.setText(_translate("LULCModel", "Linear Regression"))
        self.rbRandomForest_ModelAnalysisViewModelCoeeffcient.setText(_translate("LULCModel", "Random Forest"))
        self.pbNext_ModelAnalysis.setText(_translate("LULCModel", "Next"))
        self.gbMigrationOrder_ModelAnalysis.setTitle(_translate("LULCModel", "Migration Order (1, 2, 3, .... n)"))
        self.rbUserDefined_ModelAnalysisMigrationOrder.setText(_translate("LULCModel", "User Defined"))
        self.rbAuto_ModelAnalysisMigrationOrder.setText(_translate("LULCModel", "Auto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabModelAnalysis), _translate("LULCModel", "Model Analysis"))
        self.pbNext_DriverSelectionT1.setText(_translate("LULCModel", "Next"))
        self.gbSelectModelTypeAndDrivers_DriverSelectionT1.setTitle(_translate("LULCModel", "Select Model Type And Drivers"))
        self.rbLogisiticRegression_DriverSelectionT1SelectModelTypeAndDrivers.setText(_translate("LULCModel", "Logistic Regression"))
        self.rbNeuralRegression_DriverSelectionT1SelectModelTypeAndDrivers.setText(_translate("LULCModel", "Neural Regression"))
        self.rbIndvidualSelection_DriverSelectionT1SelectModelTypeAndDrivers.setText(_translate("LULCModel", "Individual Selection"))
        self.rbLinearRegression_DriverSelectionT1SelectModelTypeAndDrivers.setText(_translate("LULCModel", "Linear Regression"))
        self.rbRandomForest_DriverSelectionT1SelectModelTypeAndDrivers.setText(_translate("LULCModel", "Random Forest"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDriverSelectionT1), _translate("LULCModel", "Driver Selection (T2)"))
        self.pbExecute_DemandAllocation.setText(_translate("LULCModel", "Execute"))
        self.gbPolicies.setTitle(_translate("LULCModel", "Policies"))
        self.gbSpatialContext.setTitle(_translate("LULCModel", "Spatial Context"))
        self.cbInSteps_DemandAllocationSpatialContext.setItemText(0, _translate("LULCModel", "1"))
        self.lbInSteps.setText(_translate("LULCModel", "In Steps"))
        self.lbStepOutputRequired.setText(_translate("LULCModel", "Step Ouput Required"))
        self.cbStepOutputRequired_DemandAllocationSpatilaContext.setItemText(0, _translate("LULCModel", "No"))
        self.cbStepOutputRequired_DemandAllocationSpatilaContext.setItemText(1, _translate("LULCModel", "Yes"))
        self.cbEnable_DemandAllocationSpatialContext.setText(_translate("LULCModel", "Enable"))
        self.lbWindowSize.setText(_translate("LULCModel", "Window Size"))
        self.cbWindowSize_DemandAllocationSpatialContext.setItemText(0, _translate("LULCModel", "3"))
        self.cbWindowSize_DemandAllocationSpatialContext.setItemText(1, _translate("LULCModel", "5"))
        self.cbWindowSize_DemandAllocationSpatialContext.setItemText(2, _translate("LULCModel", "7"))
        self.cbUserDefinedClassInertia_DemandAllocation.setText(_translate("LULCModel", "User Defined Class Inertia (Min 0 to Max 1)"))
        self.cbUserDefinedDemand_DemandAllocation.setText(_translate("LULCModel", "User Defined Demand (Number of Pixels)"))
        self.gbSuitabilityMapGeneration.setTitle(_translate("LULCModel", "Suitability Map Generation"))
        self.lbSuitablityfile.setText(_translate("LULCModel", "SuitablityFile"))
        self.pbSelectFileSuitablityFile_OutputGenerationSuitabilityMapGeneration.setText(_translate("LULCModel", "Select File"))
        self.cbEnable_SuitabilityMapGeneration.setText(_translate("LULCModel", "Enable"))
        self.cbclassallocation_DemandAllocation.setText(_translate("LULCModel", "class allocation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDemandAllocation), _translate("LULCModel", "Output Generation"))
        self.gbDetailed_AccuracyAssesment.setTitle(_translate("LULCModel", "Detailed "))
        self.rbPreditedMapAccuracy_AccuracyAssesmentDetailed.setText(_translate("LULCModel", "Predicted Class Accuracy (User\'s Accuracy)"))
        self.rbReferenceMapReliablity_AccuracyAssesmentDetailed.setText(_translate("LULCModel", "Reference Class Reliability (Producer\'s Accuracy)"))
        self.rbConfusionMatrix_AccuracyAssesmentDetailed.setText(_translate("LULCModel", "Confusion Matrix"))
        self.gbSummary_AccuracyAssesment.setTitle(_translate("LULCModel", "Summary"))
        self.pbFindAccuracy_AccuracyAssesment.setText(_translate("LULCModel", "Find Accuracy"))
        self.pbSelectFileActualFile_AccuracyAssesment.setText(_translate("LULCModel", "Select File"))
        self.pbSelectFilePredictedFile_AccuracyAssesment.setText(_translate("LULCModel", "Select File"))
        self.label_19.setText(_translate("LULCModel", "99% C.I."))
        self.label_16.setText(_translate("LULCModel", "95% C.I."))
        self.label_17.setText(_translate("LULCModel", "95% C.I."))
        self.label_15.setText(_translate("LULCModel", "Overall Accuracy"))
        self.label_8.setText(_translate("LULCModel", "Overall Kappa"))
        self.label_18.setText(_translate("LULCModel", "No. of Observations"))
        self.label_20.setText(_translate("LULCModel", "99% C.I."))
        self.label_14.setText(_translate("LULCModel", "Reference File:"))
        self.label_11.setText(_translate("LULCModel", "Predicted File:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAccuracyAssesment), _translate("LULCModel", "Accuracy Assesment"))
        self.pbExport_ViewMaps.setText(_translate("LULCModel", "Export"))
        self.pbShow_ViewMaps.setText(_translate("LULCModel", "Show"))
        self.label_23.setText(_translate("LULCModel", "Legend Heading"))
        self.label_22.setText(_translate("LULCModel", "Title"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabViewMaps), _translate("LULCModel", "View Maps"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHelp), _translate("LULCModel", "Help"))
        self.menuMenu.setTitle(_translate("LULCModel", "Menu"))
        self.actionOpen_File.setText(_translate("LULCModel", "Open File"))
        self.actionSave_File.setText(_translate("LULCModel", "Save File"))
        self.actionExit.setText(_translate("LULCModel", "Exit"))
from PyQt5 import QtWebEngineWidgets
import resources_rc
